# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ea3e7edd4a49d501c0efa9b7f1a4483f384591c1132e602f3d1918436fe3a58b6f2070027e0b4883a0e81ae77fc75411b8bb787bfacb5d67c527390b153bee8d

test:
  secret_key_base: 2574bbbb6107b016555940b95d2a121b0f1c5dc9a0edb16f63a2e90a80052da73e1d70f9bc2c0b219a71f1e70fc8d8d64334166ad0f52bd9e4dc0606ab1231ed

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
